# URL подключения: указываем localhost, порт 3306 и имя базы из docker-compose
spring.datasource.url=jdbc:mysql://localhost:3306/spring_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
# Задаём логин и пароль, которые мы прописали в настройках Docker
spring.datasource.username=nikita_user
spring.datasource.password=nikita_password

# Настройки Hibernate для автоматического создания таблиц
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml